add_rules("mode.debug", "mode.release")

includes("3rdparty")

target("simple-infer")
    set_kind("static")
    add_includedirs("include/", { public = true })
    add_includedirs("src/")
    add_files("src/**.cpp")
    add_deps("eigen", "abseil-log", "cgraph")

target("tools")
    set_kind("static")
    add_includedirs("tools/", { public = true })
    add_files("tools/**.cpp")

-- tests
target("test-eigen")
    set_kind("binary")
    add_includedirs("src/")
    add_files("test/test_3rdparty/test_eigen.cpp")
    add_deps("simple-infer")

target("test-im2col")
    set_kind("binary")
    add_includedirs("src/")
    add_files("test/test_3rdparty/test_im2col.cpp")
    add_deps("simple-infer")

target("test-broadcast")
    set_kind("binary")
    add_includedirs("src/")
    add_files("test/test_3rdparty/test_broadcast.cpp")
    add_deps("simple-infer")

target("test-engine")
    set_kind("binary")
    add_files("test/test_engine/test_engine.cpp")
    add_defines("MODEL_PATH=R\"($(curdir)/3rdparty/tmp)\"")
    add_deps("simple-infer")

target("test-pnnx-ir")
    set_kind("binary")
    add_includedirs("src/")
    add_files("test/test_pnnx/test_pnnx_ir.cpp")
    add_defines("MODEL_PATH=R\"($(curdir)/3rdparty/tmp)\"")
    add_deps("simple-infer")

target("test-layer")
    set_kind("binary")
    add_includedirs("src/")
    add_files("test/test_main.cpp")
    add_files("test/test_layer/**.cpp")
    add_deps("simple-infer", "catch2")

target("test-yolo")
    set_kind("binary")
    add_includedirs("src/")
    add_files("test/test_yolo/test_yolo.cpp")
    add_defines("MODEL_PATH=R\"($(curdir)/3rdparty/tmp)\"")
    add_defines("IMAGE_PATH=R\"($(curdir)/imgs)\"")
    add_deps("simple-infer", "tools")

target("test-yolo2")
    set_kind("binary")
    add_includedirs("src/")
    add_files("test/test_yolo/test_yolo2.cpp")
    add_defines("MODEL_PATH=R\"($(curdir)/3rdparty/tmp)\"")
    add_defines("IMAGE_PATH=R\"($(curdir)/imgs)\"")
    add_deps("simple-infer", "tools")

target("test-classify")
    set_kind("binary")
    add_includedirs("src/")
    add_files("test/test_classify/test_classify.cpp")
    add_defines("MODEL_PATH=R\"($(curdir)/3rdparty/tmp)\"")
    add_defines("IMAGE_PATH=R\"($(curdir)/imgs)\"")
    add_deps("simple-infer", "tools")

-- benchmark
target("bench")
    set_kind("binary")
    add_includedirs("src/")
    add_files("bench/**.cpp")
    add_defines("MODEL_PATH=R\"($(curdir)/3rdparty/tmp)\"")
    add_deps("simple-infer", "benchmark")
